server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  "my client id"
            client-secret:  "my client secret"
            redirect-uri: "http://localhost:8080/auth/google/callback"
            scope:
              - email
              - profile
          kakao:
            client-id: "my client id"
            client-secret: "my client secret"
            redirect-uri: "http://localhost:8080/auth/kakao/callback"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: "Kakao"

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: my secret key